import { AIFactory, AIConfig } from "../ai/provider";
import prisma from "../prisma";

export class ProcessorAgent {
  private aiFactory: AIFactory;

  constructor(config: AIConfig) {
    this.aiFactory = new AIFactory(config);
  }

  async processRawData(days: number = 7): Promise<number> {
    console.log(`Processor Agent: Starting data organization for the last ${days} days...`);

    // 1. Fetch raw scraped data
    const dateLimit = new Date();
    dateLimit.setDate(dateLimit.getDate() - days);

    const rawData = await prisma.scrapedData.findMany({
      where: {
        createdAt: {
          gte: dateLimit
        }
      }
    });

    if (rawData.length === 0) {
      console.log(`Processor Agent: No raw data found for the last ${days} days.`);
      return 0;
    }

    console.log(`Processor Agent: Found ${rawData.length} records. sending to AI...`);

    // 2. Use AI to organize data
    // We send a summary of data to AI to avoid hitting context limits, but save all in structuredData
    const result = await this.aiFactory.process(rawData);

    if (!result.success) {
      console.error(`Processor Agent: AI Processing failed: ${result.summary}`);
    }

    // 3. Save processed data
    // Limit stored data in structuredData to 500 records to prevent DB bloat, but ensure it's a clean snippet
    const sanitizedData = Array.isArray(rawData) 
      ? JSON.parse(JSON.stringify(rawData.slice(0, 500))) 
      : [];

    await prisma.processedData.create({
      data: {
        matchDate: new Date(),
        homeTeam: "Intelligence Summary",
        awayTeam: `Analysis of ${rawData.length} matches`,
        league: "Global Intelligence",
        summary: result.summary || "No summary generated by AI.",
        structuredData: sanitizedData
      }
    });

    console.log(`Processor Agent: Successfully organized ${rawData.length} records. AI Summary length: ${result.summary?.length || 0}`);
    return rawData.length;

  }

  async cleanupOldData(days: number = 10): Promise<{ scraped: number; processed: number }> {
    const dateLimit = new Date();
    dateLimit.setDate(dateLimit.getDate() - days);

    const deletedScraped = await prisma.scrapedData.deleteMany({
      where: {
        createdAt: {
          lt: dateLimit
        }
      }
    });

    const deletedProcessed = await prisma.processedData.deleteMany({
      where: {
        createdAt: {
          lt: dateLimit
        }
      }
    });

    return {
      scraped: deletedScraped.count,
      processed: deletedProcessed.count
    };
  }
}
